version: "3"

services:

  mongodb:
    container_name: 'mongodb'
    image: "mongo"
    volumes:
      - '/data/db:/data/db'
    ports:
      - '27017:27017'

  redis:
    container_name: 'redis'
    image: 'redis'
    ports:
      - '6379:6379'

  api:
    container_name: 'coyoto-api'
    image: 'coyoto-backend'
    volumes:
      - '/home/anonymous/Documents/coding/Node/Coyoto-Backend:/home/Coyoto-Backend'
    ports:
      - '3000:3000'
    depends_on:
      - 'mongodb'
      - 'redis'
    entrypoint: 'npm run start'

  mongoExpress:
    container_name: 'mongo_express'
    image: 'mongo-express'
    ports:
      - '8081:8081'
    environment:
      - 'ME_CONFIG_MONGODB_SERVER=mongodb'