version: "3"

services:

  mongodb:
    container_name: 'mongodb'
    image: "mongo"
    volumes:
      - '/data/db:/data/db'
    ports:
      - '27017:27017'

  redis:
    container_name: 'redis'
    image: 'redis'
    ports:
      - '6378:6379'

  api:
    container_name: 'coyoto-api'
    image: 'coyoto-backend'
    volumes:
      - '/home/anonymous/Documents/coding/Node/coyoyte-backend:/home/Coyoto-Backend'
    ports:
      - '3001:3001'
    depends_on:
      - 'mongodb'
      - 'redis'
    entrypoint: 'npm run dev'
    environment:
      - 'DB_NAME=mongodb://mongodb/coyoto-app'
      - 'APP_ENV=development'
      - 'DEPLOY_ENV=localhost'
      - 'APP_PORT=3001'
      - 'REDIS_URI=redis://redis:6379'
      - 'REDIS_DB=coyote'
      - 'REDIS_PORT='
      - 'REDIS_PASS='
      - 'REDIS_HOST='

  mongoExpress:
    container_name: 'mongo_express'
    image: 'mongo-express'
    ports:
      - '8081:8081'
    environment:
      - 'ME_CONFIG_MONGODB_SERVER=mongodb'
